nginxApp:
  replicas: 6
  deploymentName: nginx-app
  containerName: nginx
  image:
    repository: us-central1-docker.pkg.dev/hardy-symbol-417822/new-repo/docker-gc
    tag: "v1"
  containerPortName: http
  containerPortNumber: 80
  containerTargetPortNumber: 80
serviceAccountName: nginx-sa
serviceName: nginx-svc