name: Package and Push Helm Charts

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
  workflow_run:
    workflows: ["Lint Helm Charts"]
    types:
      - completed
    
  pull_request:
    branches:
      - main
      - master

env: 
    PROJECT_ID: hardy-symbol-417822
    REGISTRY_LOCATION: us-central1
    REPOSITORY: app-chart

jobs:
  package_and_push:
    name: Package and Push Helm Charts
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          helm-version: 'latest'

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          token_format: "access_token"
      
      - name: Package Helm Charts
        run: |
          helm package asels-app/ -d ./packaged-charts

      - name: Push Helm Charts
        run: |
          helm push ./packaged-charts/*.tgz "oci://us-central1-docker.pkg.dev/hardy-symbol-417822/new-repo"