name: Lint Helm Charts
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          helm-version: 'latest'

      - name: Lint Helm Charts
        run: |
          for chart in $(find . -name "Chart.yaml" -exec dirname {} \;); do
            helm lint $chart
          done
